p = input('Digite alguma coisa: ')
print(f'O tipo primitivo deste valor é {type(p)}')
print(f'Só tem espaços? {p.isspace()}')
print(f'É um número? {p.isnumeric()}')
print(f'É alfabético? {p.isalpha()}')
print(f'É alfanumérico? {p.isalnum()}')
print(f'Está em maiúsculas? {p.isupper()}')
print(f'Está em minúsculas? {p.islower()}')
print(f'Está capitalizada? {p.istitle()}')